import requests
import os

# --- 配置区域 ---
# 1. 来源链接：这里使用 GitHub 上常见的 geosite 规则源（例如 Loyalsoldier 或者你提供的特定源）
# 如果你有特定的 raw 链接，请替换下面这个 URL
SOURCE_URL = "https://raw.githubusercontent.com/v2fly/domain-list-community/refs/heads/master/data/bytedance"

# 2. 目标文件：PaoPaoDNS 读取的文件名
OUTPUT_FILE = "force_ttl_rules.txt"

# 3. 指定的 DNS 服务器：字节跳动权威 DNS
TARGET_DNS = "180.184.1.1:53"
# ----------------

def fetch_and_process():
    print(f"正在获取规则: {SOURCE_URL}")
    try:
        response = requests.get(SOURCE_URL, timeout=10)
        response.raise_for_status()
        content = response.text
    except Exception as e:
        print(f"下载失败: {e}")
        return

    valid_lines = []
    
    # 手动添加一些关键域名，防止源文件中遗漏
    custom_domains = [
        "douyin.com",
        "snssdk.com",
        "ixigua.com",
        "pstatp.com",
        "toutiao.com",
        "byteimg.com",
        "amemv.com"
    ]

    # 处理下载的内容
    for line in content.splitlines():
        line = line.strip()
        
        # 过滤注释、空行和 include 指令
        if not line or line.startswith("#") or line.startswith("include:"):
            continue
            
        # 处理行内修饰符，例如 "byteoversea.com @!cn" -> "byteoversea.com"
        domain = line.split()[0]
        
        # 处理 full: 前缀，例如 "full:example.com" -> "example.com"
        if domain.startswith("full:"):
            domain = domain.replace("full:", "")
            
        # 简单的去重检查（由于后面会统一去重，这里只需确保提取正确）
        if "." in domain: 
            custom_domains.append(domain)

    # 去重并排序
    unique_domains = sorted(list(set(custom_domains)))
    
    print(f"共提取到 {len(unique_domains)} 个域名")

    # 写入文件
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        # 写入文件头部注释（可选）
        f.write(f"# Auto generated by GitHub Actions\n")
        f.write(f"# Target DNS: {TARGET_DNS}\n\n")
        
        for domain in unique_domains:
            # 格式化为 PaoPaoDNS 格式: domain@IP:PORT
            rule_line = f"{domain}@{TARGET_DNS}\n"
            f.write(rule_line)
            
    print(f"文件已生成: {OUTPUT_FILE}")

if __name__ == "__main__":
    fetch_and_process()