# .github/workflows/generate_gist.yml

name: Generate Private Clash Gist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-gist:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出您的仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 使用 sed 命令替换占位符
      - name: Replace URL placeholders
        run: |
          sed -i 's|__MEIYING_URL__|${{ secrets.MEIYING_URL }}|g' mihomo.yaml
          sed -i 's|__YUNDONG_URL__|${{ secrets.YUNDONG_URL }}|g' mihomo.yaml
        env:
          MEIYING_URL: ${{ secrets.MEIYING_URL }}
          YUNDONG_URL: ${{ secrets.YUNDONG_URL }}

      # 3. 使用官方 GitHub CLI 创建或更新 Gist
      - name: Create or Update Private Gist using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          if [[ -z "$GIST_ID" ]]; then
            echo "GIST_ID not found. Creating a new secret Gist..."
            # 修正：移除了错误的 --private 参数。默认就是创建 secret Gist。
            gh gist create mihomo.yaml --desc "Private Clash Configuration"
            echo "------------------------------------------------------------------"
            echo "IMPORTANT: A new Gist has been created."
            echo "Please go to your Gist page (https://gist.github.com), find the new Gist,"
            echo "and copy its ID from the URL (e.g., a0b1c2d3e4f5...)."
            echo "Then, create a new repository secret named 'GIST_ID' with this value for future updates."
            echo "------------------------------------------------------------------"
          else
            echo "GIST_ID found. Updating existing Gist..."
            gh gist edit "$GIST_ID" mihomo.yaml --filename "mihomo-private.yaml"
            echo "Gist updated successfully."
          fi
