# 工作流的名称
name: Sync External Lists (Optimized)

# 控制工作流触发的条件
on:
  # 允许您从“Actions”选项卡手动运行此工作流
  workflow_dispatch:

  # 设置定时任务，使用 cron 语法
  # 这里的 '0 1 * * *' 表示每天的 UTC 时间 1:00 运行
  schedule:
    - cron: '0 1 * * *'

# 定义一个或多个作业（job）
jobs:
  # 作业的唯一ID
  sync-job:
    # 作业运行的虚拟环境
    runs-on: ubuntu-latest

    # 作业中包含的一系列步骤
    steps:
      # 第一步：检出（checkout）您的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：拉取远程文件并进行格式化处理
      - name: Fetch, process, and combine external lists
        run: |
          # 定义目标文件名和临时文件名
          TARGET_FILE="ChinaMerged.list"
          TEMP_FILE=$(mktemp)
          
          # 定义要拉取的远程文件URL列表
          URLS=(
            "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
            "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
            "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
            "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"
            "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaIpV6.list"
          )
          
          # 循环遍历URL列表，下载内容并追加到临时文件中
          for url in "${URLS[@]}"; do
            echo "Fetching from $url"
            # 使用 curl 下载文件内容 (-L 处理重定向, -sS 静默但显示错误)
            # 将下载的内容追加到临时文件中
            curl -L -sS "$url" >> $TEMP_FILE || echo "Warning: Failed to fetch $url"
          done
          
          echo "Processing and cleaning the combined list..."
          # 核心处理步骤：
          # 1. cat $TEMP_FILE: 读取合并后的原始文件内容。
          # 2. grep -vE '(^#|^\s*$)': 过滤掉所有注释行(以#开头)和空行。
          # 3. sort -u: 对结果进行排序并移除重复行。
          # 4. > $TARGET_FILE: 将最终干净、有序、唯一的结果写入目标文件。
          cat $TEMP_FILE | grep -vE '(^#|^\s*$)' | sort -u > $TARGET_FILE
          
          # 清理临时文件
          rm $TEMP_FILE
          
          echo "Cleaned, sorted, and unique list has been saved to $TARGET_FILE"

      # 第三步：提交并推送文件更改
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 提交信息
          commit_message: 'docs(lists): 自动同步并格式化列表文件'
          
          # 要提交的文件名，已更新为 .list
          file_pattern: 'ChinaMerged.list'
          
          # 提交者和作者的 git 用户信息
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>

